services:
  database:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: lanchonete

volumes:
  db-data: { }